name: Check PR health

on: [push]

jobs:
  check-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install packages
        run: yarn
      
      - name: Check linting and fix
        run: yarn run lint:fix

      - name: Commit and push if it changed
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          commit-message: "eslint: fix linting healthy"
          title: "Fix linting error"
          body: "fix error eslint"
        